dbt_tpcds:
  outputs:
    dev:
      account: <Your Snowflake Account Name>
      database: TPCDS
      password: <Your Snowflake Password>
      role: AccountAdmin
      schema: RAW
      threads: 1
      type: snowflake
      user: <Your Snowflake User Name>
      warehouse: COMPUTE_WH
  target: dev
